const nameFactory = (filter=false) => {

    let singles = [
        "Antoinette",
        "Lady",
        "Maiden",
        "Emily Elizabeth the XIVV",
        "Declan",
        "The Elusive Matthew Santoro",
        "MoonGazer",
        "Purity",
        "King",
        "Seeker of Faults",
        "Arcanine",
        "Jellyfish",
        "Baby Shark",
        "Of Depths and Sparkle",
        "Popocatepetl",
        "North Star",
        "White Elephant",
        "Black Cat",
        "Harbringer of Doom",
        "Split Line",
        "Enduring Will",
        "Spitfire",
        "Lighting Rod",
        "Fisherman's Ferry",
        "Fisher",
        "Crabber's Nightmare",
        "Nightmare",
        "Stallion",
        "La Rose Vielle",
        "Intensity",
        "Strange Fruit",
        "superfruit",
        "Dragon Druit",
        "Triple G",
        "The Finest Trader",
        "Queen's Caravel",
        "Northern Serenity",
        "Southern Serenity",
        "Eastpoint",
        "Catrina Calavera",
        "Skalleon",
        "Spear Point",
        "Thump Thump",
        "Mercy",
        "Slaughter",
        "Braiser",
        "Wash Cycle",
        "Chantilly",
        "Chicago",
        "De las Cuevas",
        "Barbed Lance",
        "Branding Iron",
        "Addison Amy",
    ]
    let starters = [
        "S.S",
        "The Grand",
        "Puny",
        "Tiny",
        "Ferryboat",
        "Dreamboat",
        "Cruiser",
        "The",
        "Hulking",
        "Iron",
        "Seaworthy",
        "Star",
        "Navigator",
        "Fine Line",
        "Warrior",
        "The Impeccable",
        "The Unsinkable",
        "Burning",
        "Ghastly",
        "Evil",
        "Angellic",
        "Demonic",
    ]
    let enders = [
        "Annie",
        "Anne",
        "Amy",
        "Antoinette",
        "Antonella",
        "Berriche",
        "Bernadette",
        "Baby",
        "Beacher",
        "Ballast",
        "Beppi the Clown",
        "Ben 10",
        "Benny the Great",
        "Carrier",
        "Carter",
        "Commisiner",
        "Crack",
        "Demon",
        "Davita",
        "Davy Jones",
        "Eleanor",
        "Estefania",
        "Enterprise",
        "Falcon",
        "Fox",
        "Fighter",
        "Felicia",
        "Felicity",
        "Georgia",
        "Gregoria",
        "Groveller",
        "Harriet",
        "Harima",
        "Intuition",
        "Isabelle",
        "Ice",
        "Jamie",
        "Juliette",
        "Julianne",
        "Julie",
        "Karina",
        "Karin",
        "Kraken",
        "Lorena",
        "Letizia",
        "Layman",
        "Line",
        "Marybell",
        "Martina",
        "Moon",
        "Natasia",
        "NightLight",
        "Nighthawk",
        "Merry",
        "Mary",
        "Mordecai",
        "Margaret always mar-gets the bad guys",
        "Margaret",
        "Mary-Anne-Shelley-van-de-Vaart",
        "Ophelia",
        "Oddessy",
        "Odessa",
        "Pruin",
        "Paloma",
        "Pam",
        "Quicksilver",
        "Rash",
        "Rovia",
        "Rover",
        "Star",
        "Steven Universe",
        "Seeker",
        "Weezer",
        "Samantha",
        "Thea-Rose",
        "Tio",
        "Thimble",
        "Undertaker",
        "Violet",
        "Violetta",
        "Veronica",
        "Vanessa",
        "Wanda",
        "Wander",
        "Xiomara",
        "Yvonne",
        "Yonder",
        "Zulekia",
        "Zaffron",
        "Purity",
        "Declan",
        "Messiah",
        "Raider",
        "Bandit",
        "Shifter",
        "Shaker",
        "Ally",
        "Breaker",
        "Ferreria"
    ]

    let generatedPrefix = starters[Math.floor(Math.random() * starters.length)];
    let generatedSuffix = enders[Math.floor(Math.random() * enders.length)];

    let selectedRandom = singles[Math.floor(Math.random() * singles.length)];

    let generatedName = `${generatedPrefix} ${generatedSuffix}`;

    let selectedNames = [generatedName, selectedRandom];

    let selectedName = selectedNames[Math.floor(Math.random() * selectedNames.length)];

    return selectedName;
}

export default nameFactory;